USE [Europe Sales Data]
GO

CREATE FUNCTION func_MONTHNAME (@DATE DATE)
RETURNS VARCHAR(9)
AS
BEGIN
	DECLARE @MONTHNAME VARCHAR(9);
	SELECT  @MONTHNAME = (
			CASE
			WHEN MONTH(@DATE) = 1 THEN 'JANUARY'
			WHEN MONTH(@DATE) = 2 THEN 'FEBRUARY'
			WHEN MONTH(@DATE) = 3 THEN 'MARCH'
			WHEN MONTH(@DATE) = 4 THEN 'APRIL'
			WHEN MONTH(@DATE) = 5 THEN 'MAY'
			WHEN MONTH(@DATE) = 6 THEN 'JUNE'
			WHEN MONTH(@DATE) = 7 THEN 'JULY'
			WHEN MONTH(@DATE) = 8 THEN 'AUGUST'
			WHEN MONTH(@DATE) = 9 THEN 'SEPTEMBER'
			WHEN MONTH(@DATE) = 10 THEN 'OCTOBER'
			WHEN MONTH(@DATE) = 11 THEN 'NOVEMBER'
			WHEN MONTH(@DATE) = 12 THEN 'DECEMBER'
			END)
	RETURN @MONTHNAME
END;