USE [Europe Sales Data]
GO

CREATE FUNCTION func_WEEKDAYNAME (@DATE DATE)
RETURNS VARCHAR(9)
AS
BEGIN
	DECLARE @WEEKDAYNAME VARCHAR(9);
	SELECT  @WEEKDAYNAME = (
			CASE
			WHEN DATEPART(DW, @DATE) = 1 THEN 'MONDAY'
			WHEN DATEPART(DW, @DATE) = 2 THEN 'TUESDAY'
			WHEN DATEPART(DW, @DATE) = 3 THEN 'WEDNESDAY'
			WHEN DATEPART(DW, @DATE) = 4 THEN 'THURSDAY'
			WHEN DATEPART(DW, @DATE) = 5 THEN 'FRIDAY'
			WHEN DATEPART(DW, @DATE) = 6 THEN 'SATURDAY'
			WHEN DATEPART(DW, @DATE) = 7 THEN 'SUNDAY'
			END)
	RETURN @WEEKDAYNAME
END;