name: Power BI Report Overwrite
on:
  # This triggers when Europe Sales Report.pbix is pushed to in this branch t
  push:
    paths: 
      - ./Europe Sales Report.pbix
  # This workflow can also be run manually via button in the 
  workflow_dispatch:

jobs:
  PowerBIps1Overwrite:
    runs-on: ubuntu-latest
    env:
          POWERBISPPWD: ${{secrets.POWERBISPPWD}}
          JFTECHTENANTID: ${{secrets.JFTECHTENANTID}}
          ESRWKSPID: ${{secrets.ESRWKSPID}}
          POWERBIAPPID: ${{secrets.POWERBIAPPID}}
    steps:
      - uses: actions/checkout@v4
      - name: Build Module
        shell: pwsh
        run: ./PowerBIOverwrite.ps1
