name: Power BI Report Overwrite
on:
  push:
    paths: 
      - ./Europe Sales Report.pbix

jobs:
  PowerBIps1Overwrite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Module
        shell: pwsh
        run: ./PowerBIOverwrite.ps1
