Name: Power BI Report Overwrite
ON: push

jobs:
  PowerBIPS1Overwrite:
    runs-on: ubuntu-latest

      steps: 
        - name: Build Module
          shell: pwsh
          run: ./PowerBIOverwrite.ps1
